version: '3'
services:
        web:
                image: ggaib
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8763:8763"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped